
import fs from 'fs';
import path from 'path';
import striptags from 'striptags';

const APP_DIR = path.join(process.cwd(), 'app');
const DATA_DIR = path.join(process.cwd(), 'data');
const BLOG_DIR = path.join(APP_DIR, 'blog', '(articles)');
const WORK_DIR = path.join(APP_DIR, 'work');
const OUTPUT_FILE = path.join(process.cwd(), 'lib', 'generated-context.ts');

function cleanText(text: string): string {
    // Remove import statements
    text = text.replace(/^import .*$/gm, '');
    // Remove export statements
    text = text.replace(/^export .*$/gm, '');
    // Remove frontmatter
    text = text.replace(/^---[\s\S]*?---/m, '');

    // Strip tags but keep text
    text = striptags(text);

    // Collapse multiple newlines/spaces
    return text.replace(/\s+/g, ' ').trim();
}

function getBlogContent(): string {
    if (!fs.existsSync(BLOG_DIR)) return '';

    const files = fs.readdirSync(BLOG_DIR).filter(f => f.endsWith('.mdx') || f.endsWith('.md'));
    let content = "## BLOG POSTS\n\n";

    for (const file of files) {
        const raw = fs.readFileSync(path.join(BLOG_DIR, file), 'utf-8');
        content += `### ${file}\n${cleanText(raw)}\n\n`;
    }
    return content;
}

function getPageContent(filePath: string, title: string): string {
    const fullPath = path.join(APP_DIR, filePath);
    if (!fs.existsSync(fullPath)) return '';

    const raw = fs.readFileSync(fullPath, 'utf-8');
    return `## PAGE: ${title}\n\n${cleanText(raw)}\n\n`;
}

function getWorkContent(): string {
    if (!fs.existsSync(WORK_DIR)) return '';

    let content = "## WORK PORTFOLIO\n\n";

    // Read subdirectories in work/
    const projects = fs.readdirSync(WORK_DIR).filter(f => fs.statSync(path.join(WORK_DIR, f)).isDirectory());

    for (const project of projects) {
        const pagePath = path.join(WORK_DIR, project, 'page.tsx');
        if (fs.existsSync(pagePath)) {
            const raw = fs.readFileSync(pagePath, 'utf-8');
            content += `### PROJECT: ${project}\n${cleanText(raw)}\n\n`;
        }
    }

    return content;
}

function getBookContent(): string {
    const bookPath = path.join(DATA_DIR, 'book.md');
    const bookTxtPath = path.join(DATA_DIR, 'book.txt');

    if (fs.existsSync(bookPath)) {
        return `## BOOK: The Pharmacology of Silence\n\n${fs.readFileSync(bookPath, 'utf-8')}\n\n`;
    } else if (fs.existsSync(bookTxtPath)) {
        return `## BOOK: The Pharmacology of Silence\n\n${fs.readFileSync(bookTxtPath, 'utf-8')}\n\n`;
    }

    return '';
}

async function main() {
    console.log('Generating context...');

    let fullContext = "";

    // 1. Who Am I Page
    fullContext += getPageContent('who-am-i/page.tsx', 'Who Am I');

    // 2. Work Portfolio (All Projects)
    fullContext += getWorkContent();

    // 3. Blog Posts
    fullContext += getBlogContent();

    // 4. Book
    fullContext += getBookContent();


    const fileContent = `// Auto-generated by scripts/generate-context.ts
export const FULL_CONTEXT = \`
${fullContext.replace(/`/g, '\\`').replace(/\$\{/g, '\\${')}
\`;
`;

    fs.writeFileSync(OUTPUT_FILE, fileContent);
    console.log(`Context generated at ${OUTPUT_FILE} (${fullContext.length} chars)`);
}

main().catch(console.error);
